// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.19.6
// source: vmi_stream.proto

package vmi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AlertForwarder_PushAlert_FullMethodName = "/vmi.AlertForwarder/PushAlert"
)

// AlertForwarderClient is the client API for AlertForwarder service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AlertForwarderClient interface {
	PushAlert(ctx context.Context, in *Alert, opts ...grpc.CallOption) (*Ack, error)
}

type alertForwarderClient struct {
	cc grpc.ClientConnInterface
}

func NewAlertForwarderClient(cc grpc.ClientConnInterface) AlertForwarderClient {
	return &alertForwarderClient{cc}
}

func (c *alertForwarderClient) PushAlert(ctx context.Context, in *Alert, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, AlertForwarder_PushAlert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AlertForwarderServer is the server API for AlertForwarder service.
// All implementations must embed UnimplementedAlertForwarderServer
// for forward compatibility.
type AlertForwarderServer interface {
	PushAlert(context.Context, *Alert) (*Ack, error)
	mustEmbedUnimplementedAlertForwarderServer()
}

// UnimplementedAlertForwarderServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAlertForwarderServer struct{}

func (UnimplementedAlertForwarderServer) PushAlert(context.Context, *Alert) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method PushAlert not implemented")
}
func (UnimplementedAlertForwarderServer) mustEmbedUnimplementedAlertForwarderServer() {}
func (UnimplementedAlertForwarderServer) testEmbeddedByValue()                        {}

// UnsafeAlertForwarderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AlertForwarderServer will
// result in compilation errors.
type UnsafeAlertForwarderServer interface {
	mustEmbedUnimplementedAlertForwarderServer()
}

func RegisterAlertForwarderServer(s grpc.ServiceRegistrar, srv AlertForwarderServer) {
	// If the following call panics, it indicates UnimplementedAlertForwarderServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AlertForwarder_ServiceDesc, srv)
}

func _AlertForwarder_PushAlert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Alert)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AlertForwarderServer).PushAlert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AlertForwarder_PushAlert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AlertForwarderServer).PushAlert(ctx, req.(*Alert))
	}
	return interceptor(ctx, in, info, handler)
}

// AlertForwarder_ServiceDesc is the grpc.ServiceDesc for AlertForwarder service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AlertForwarder_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vmi.AlertForwarder",
	HandlerType: (*AlertForwarderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PushAlert",
			Handler:    _AlertForwarder_PushAlert_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vmi_stream.proto",
}
