// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.6
// source: vmi_stream.proto

package vmi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Alert struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pid           uint32                 `protobuf:"varint,1,opt,name=pid,proto3" json:"pid,omitempty"`
	ThreatType    string                 `protobuf:"bytes,2,opt,name=threat_type,json=threatType,proto3" json:"threat_type,omitempty"`
	Confidence    float32                `protobuf:"fixed32,3,opt,name=confidence,proto3" json:"confidence,omitempty"`
	ThreatLevel   uint32                 `protobuf:"varint,4,opt,name=threat_level,json=threatLevel,proto3" json:"threat_level,omitempty"`
	TimestampNs   uint64                 `protobuf:"varint,5,opt,name=timestamp_ns,json=timestampNs,proto3" json:"timestamp_ns,omitempty"`
	Reason        string                 `protobuf:"bytes,6,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Alert) Reset() {
	*x = Alert{}
	mi := &file_vmi_stream_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Alert) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Alert) ProtoMessage() {}

func (x *Alert) ProtoReflect() protoreflect.Message {
	mi := &file_vmi_stream_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Alert.ProtoReflect.Descriptor instead.
func (*Alert) Descriptor() ([]byte, []int) {
	return file_vmi_stream_proto_rawDescGZIP(), []int{0}
}

func (x *Alert) GetPid() uint32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *Alert) GetThreatType() string {
	if x != nil {
		return x.ThreatType
	}
	return ""
}

func (x *Alert) GetConfidence() float32 {
	if x != nil {
		return x.Confidence
	}
	return 0
}

func (x *Alert) GetThreatLevel() uint32 {
	if x != nil {
		return x.ThreatLevel
	}
	return 0
}

func (x *Alert) GetTimestampNs() uint64 {
	if x != nil {
		return x.TimestampNs
	}
	return 0
}

func (x *Alert) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_vmi_stream_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_vmi_stream_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_vmi_stream_proto_rawDescGZIP(), []int{1}
}

func (x *Ack) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_vmi_stream_proto protoreflect.FileDescriptor

const file_vmi_stream_proto_rawDesc = "" +
	"\n" +
	"\x10vmi_stream.proto\x12\x03vmi\"\xb8\x01\n" +
	"\x05Alert\x12\x10\n" +
	"\x03pid\x18\x01 \x01(\rR\x03pid\x12\x1f\n" +
	"\vthreat_type\x18\x02 \x01(\tR\n" +
	"threatType\x12\x1e\n" +
	"\n" +
	"confidence\x18\x03 \x01(\x02R\n" +
	"confidence\x12!\n" +
	"\fthreat_level\x18\x04 \x01(\rR\vthreatLevel\x12!\n" +
	"\ftimestamp_ns\x18\x05 \x01(\x04R\vtimestampNs\x12\x16\n" +
	"\x06reason\x18\x06 \x01(\tR\x06reason\"\x1f\n" +
	"\x03Ack\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess23\n" +
	"\x0eAlertForwarder\x12!\n" +
	"\tPushAlert\x12\n" +
	".vmi.Alert\x1a\b.vmi.AckB\n" +
	"Z\b./pb/vmib\x06proto3"

var (
	file_vmi_stream_proto_rawDescOnce sync.Once
	file_vmi_stream_proto_rawDescData []byte
)

func file_vmi_stream_proto_rawDescGZIP() []byte {
	file_vmi_stream_proto_rawDescOnce.Do(func() {
		file_vmi_stream_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_vmi_stream_proto_rawDesc), len(file_vmi_stream_proto_rawDesc)))
	})
	return file_vmi_stream_proto_rawDescData
}

var file_vmi_stream_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_vmi_stream_proto_goTypes = []any{
	(*Alert)(nil), // 0: vmi.Alert
	(*Ack)(nil),   // 1: vmi.Ack
}
var file_vmi_stream_proto_depIdxs = []int32{
	0, // 0: vmi.AlertForwarder.PushAlert:input_type -> vmi.Alert
	1, // 1: vmi.AlertForwarder.PushAlert:output_type -> vmi.Ack
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_vmi_stream_proto_init() }
func file_vmi_stream_proto_init() {
	if File_vmi_stream_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_vmi_stream_proto_rawDesc), len(file_vmi_stream_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_vmi_stream_proto_goTypes,
		DependencyIndexes: file_vmi_stream_proto_depIdxs,
		MessageInfos:      file_vmi_stream_proto_msgTypes,
	}.Build()
	File_vmi_stream_proto = out.File
	file_vmi_stream_proto_goTypes = nil
	file_vmi_stream_proto_depIdxs = nil
}
